using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LogicomDevisFrontEnd.Models
{
    public class Client
    {
        public string code { get; set; }
        public string rsoc { get; set; }
        public string adresse { get; set; }
        public string cp { get; set; }
        public string descp { get; set; }
        public string ville { get; set; }
        public string pays { get; set; }
        public string telephone { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string site { get; set; }
        public string matriculef { get; set; }
        public string banque { get; set; }
        public string compteb { get; set; }
        public string comptec { get; set; }
        public string cltexport { get; set; }
        public string timbref { get; set; }
        public string exon { get; set; }
        public string majotva { get; set; }
        public string suspfodec { get; set; }
        public string responsable1 { get; set; }
        public string responsable2 { get; set; }
        public string responsable3 { get; set; }
        public string titre1 { get; set; }
        public string titre2 { get; set; }
        public string titre3 { get; set; }
        public string gsm1 { get; set; }
        public string gsm2 { get; set; }
        public string gsm3 { get; set; }
        public string nposte1 { get; set; }
        public string nposte2 { get; set; }
        public string nposte3 { get; set; }
        public string tarif { get; set; }
        public string offretick { get; set; }
        public string Adresse1 { get; set; }
        public string Commentaire { get; set; }
        public string bon { get; set; }
        public string cin { get; set; }
        public string typecli { get; set; }
        public string emp { get; set; }
        public string seloffre { get; set; }
        public string susptva { get; set; }
        public string decision { get; set; }
        public Nullable<System.DateTime> datec { get; set; }
        public string activite { get; set; }
        public string coder { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string telex { get; set; }
        public string codes { get; set; }
        public string nature { get; set; }
        public Nullable<double> remise { get; set; }
        public string typreg { get; set; }
        public Nullable<double> scredit { get; set; }
        public Nullable<double> srisque { get; set; }
        public string coderep { get; set; }
        public string desrep { get; set; }
        public Nullable<double> mtdebit { get; set; }
        public Nullable<double> mtcredit { get; set; }
        public Nullable<double> soldeini { get; set; }
        public Nullable<double> solde { get; set; }
        public string blockage { get; set; }
        public string desisec { get; set; }
        public string desireg { get; set; }
        public string desicp { get; set; }
        public Nullable<double> ventiler { get; set; }
        public Nullable<double> livcours { get; set; }
        public Nullable<double> totregle { get; set; }
        public string aval1 { get; set; }
        public string aval2 { get; set; }
        public Nullable<System.DateTime> datecin { get; set; }
        public Nullable<double> soldeinibs { get; set; }
        public string rsocar { get; set; }
        public string adressear { get; set; }
        public Nullable<double> soldebs { get; set; }
        public string fidel { get; set; }
        public Nullable<System.DateTime> datefidel { get; set; }
        public Nullable<double> remfidel { get; set; }
        public string typcarte { get; set; }
        public string Matricule { get; set; }
        public string numcarte { get; set; }
        public Nullable<double> tauxconv { get; set; }
        public Nullable<System.DateTime> datcreat { get; set; }
        public Nullable<System.DateTime> datexp { get; set; }
        public Nullable<double> chifaff { get; set; }
        public Nullable<double> nbrpts { get; set; }
        public Nullable<double> catot { get; set; }
        public Nullable<System.DateTime> dernclot { get; set; }
        public Nullable<double> soldeinitexer { get; set; }
        public string connaiss { get; set; }
        public string profession { get; set; }
        public string premAch { get; set; }
        public Nullable<long> nbreEnf { get; set; }
        public Nullable<System.DateTime> dat1 { get; set; }
        public Nullable<System.DateTime> dat2 { get; set; }
        public Nullable<System.DateTime> dat3 { get; set; }
        public Nullable<System.DateTime> dat4 { get; set; }
        public string nom1 { get; set; }
        public string nom2 { get; set; }
        public string nom3 { get; set; }
        public string nom4 { get; set; }
        public string opf1 { get; set; }
        public string opf2 { get; set; }
        public string opf3 { get; set; }
        public string opf4 { get; set; }
        public string rsocconj { get; set; }
        public Nullable<System.DateTime> datnaissconj { get; set; }
        public string professconj { get; set; }
        public Nullable<System.DateTime> datnaiss { get; set; }
        public Nullable<System.DateTime> datedebaut { get; set; }
        public Nullable<System.DateTime> datefinaut { get; set; }
        public string typcli { get; set; }
        public string regime { get; set; }
        public Nullable<double> soldeinidevise { get; set; }
        public string usera { get; set; }
        public string userm { get; set; }
        public string users { get; set; }
        public Nullable<System.DateTime> datemaj { get; set; }
        public Nullable<double> soldeinibl { get; set; }
        public Nullable<double> soldebl { get; set; }
        public Nullable<double> sdinilivencours { get; set; }
        public Nullable<double> totreglesd { get; set; }
        public Nullable<double> soldecont { get; set; }
        public string blnbon { get; set; }
        public double? NbPtsFid { get; set; }
        public string codepv { get; set; }
        public string contrat { get; set; }
        public Nullable<double> fact { get; set; }
        public string comptec2 { get; set; }
        public string ptva { get; set; }
        public string reference { get; set; }
        public string codesel { get; set; }
        public double soldeiniRapp { get; set; }
        public double totreglerapp { get; set; }
        public string NPermis { get; set; }
        public string TypePermis { get; set; }
        public string DatePermis { get; set; }
        public string ParPermis { get; set; }
        public string ParCin { get; set; }
        public int? delregFT { get; set; }
        public int? delregFC { get; set; }
        public int? delregBL { get; set; }

  
        public  List<Devis> Devis { get; set; }
    }
}