//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicomDevisBackEnd.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class somabeEntities : DbContext
    {
        public somabeEntities()
            : base("name=somabeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<dfp> dfp { get; set; }
        public virtual DbSet<famille> famille { get; set; }
        public virtual DbSet<ldfp> ldfp { get; set; }
        public virtual DbSet<depot> depot { get; set; }
        public virtual DbSet<lignedepot> lignedepot { get; set; }
        public virtual DbSet<pointvente> pointvente { get; set; }
        public virtual DbSet<societe> societe { get; set; }
    }
}
