//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicomDevisBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lignedepot
    {
        public string codedep { get; set; }
        public string codeart { get; set; }
        public string libelle { get; set; }
        public string desart { get; set; }
        public string famille { get; set; }
        public Nullable<double> qteart { get; set; }
        public Nullable<double> stockinitial { get; set; }
        public Nullable<double> stockmin { get; set; }
        public Nullable<double> stockmax { get; set; }
        public string typearticle { get; set; }
        public Nullable<double> qteres { get; set; }
        public string numfourn { get; set; }
        public string libfourn { get; set; }
        public Nullable<System.DateTime> datderninv { get; set; }
        public string type { get; set; }
        public string artmouv { get; set; }
        public string lot { get; set; }
        public string codepv { get; set; }
        public string libpv { get; set; }
        public string lieustock { get; set; }
        public string sousfamille { get; set; }
        public Nullable<double> qtereap { get; set; }
        public Nullable<byte> isSelected { get; set; }
        public string numInventaireCourant { get; set; }
    
        public virtual article Article { get; set; }
    }
}
