//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicomDevisBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class representant
    {
        public string Code { get; set; }
        public Nullable<System.DateTime> datec { get; set; }
        public string rsoc { get; set; }
        public string adresse { get; set; }
        public string adresse1 { get; set; }
        public string region { get; set; }
        public Nullable<System.DateTime> ddc { get; set; }
        public string cin { get; set; }
        public string tel { get; set; }
        public Nullable<double> marge { get; set; }
        public string commentaire { get; set; }
        public string login { get; set; }
        public string motpasse { get; set; }
        public string fonction { get; set; }
        public string piece { get; set; }
        public string codequal { get; set; }
        public string libqual { get; set; }
        public string fax { get; set; }
        public string mobile { get; set; }
        public string mail { get; set; }
        public Nullable<double> cout { get; set; }
        public Nullable<System.DateTime> dateemb { get; set; }
        public string regime { get; set; }
        public string caisse { get; set; }
        public Nullable<double> actif { get; set; }
        public Nullable<double> commsupp { get; set; }
        public Nullable<double> nbjr { get; set; }
        public string confid { get; set; }
        public string impcaisse { get; set; }
        public string CODESEL { get; set; }
        public Nullable<int> commission_kw { get; set; }
    }
}
