//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicomDevisBackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usersoc
    {
        public string CODEUSER { get; set; }
        public string societe { get; set; }
        public string accee { get; set; }
        public string ecriture { get; set; }
        public string Projet { get; set; }
        public string seltmp { get; set; }
        public string acceclot { get; set; }
        public string rsoc { get; set; }
        public string ip { get; set; }
    }
}
